/**
 * generated by Xtext 2.38.0
 */
package fr.n7.pDL3.impl;

import fr.n7.pDL3.PDL3Package;
import fr.n7.pDL3.ProcessElement;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Process Element</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class ProcessElementImpl extends MinimalEObjectImpl.Container implements ProcessElement
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProcessElementImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PDL3Package.Literals.PROCESS_ELEMENT;
  }

} //ProcessElementImpl
