/**
 * generated by Xtext 2.38.0
 */
package fr.n7.pDL3.impl;

import fr.n7.pDL3.PDL3Package;
import fr.n7.pDL3.ProcessElement;
import fr.n7.pDL3.WorkDefinition;
import fr.n7.pDL3.WorkSequence;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Process</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.pDL3.impl.ProcessImpl#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.pDL3.impl.ProcessImpl#getWorkDefinitions <em>Work Definitions</em>}</li>
 *   <li>{@link fr.n7.pDL3.impl.ProcessImpl#getWorkSequences <em>Work Sequences</em>}</li>
 *   <li>{@link fr.n7.pDL3.impl.ProcessImpl#getProcessElements <em>Process Elements</em>}</li>
 * </ul>
 *
 * @generated
 */
public class ProcessImpl extends MinimalEObjectImpl.Container implements fr.n7.pDL3.Process
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getWorkDefinitions() <em>Work Definitions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWorkDefinitions()
   * @generated
   * @ordered
   */
  protected EList<WorkDefinition> workDefinitions;

  /**
   * The cached value of the '{@link #getWorkSequences() <em>Work Sequences</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getWorkSequences()
   * @generated
   * @ordered
   */
  protected EList<WorkSequence> workSequences;

  /**
   * The cached value of the '{@link #getProcessElements() <em>Process Elements</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getProcessElements()
   * @generated
   * @ordered
   */
  protected EList<ProcessElement> processElements;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected ProcessImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return PDL3Package.Literals.PROCESS;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, PDL3Package.PROCESS__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<WorkDefinition> getWorkDefinitions()
  {
    if (workDefinitions == null)
    {
      workDefinitions = new EObjectContainmentEList<WorkDefinition>(WorkDefinition.class, this, PDL3Package.PROCESS__WORK_DEFINITIONS);
    }
    return workDefinitions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<WorkSequence> getWorkSequences()
  {
    if (workSequences == null)
    {
      workSequences = new EObjectContainmentEList<WorkSequence>(WorkSequence.class, this, PDL3Package.PROCESS__WORK_SEQUENCES);
    }
    return workSequences;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<ProcessElement> getProcessElements()
  {
    if (processElements == null)
    {
      processElements = new EObjectContainmentEList<ProcessElement>(ProcessElement.class, this, PDL3Package.PROCESS__PROCESS_ELEMENTS);
    }
    return processElements;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case PDL3Package.PROCESS__WORK_DEFINITIONS:
        return ((InternalEList<?>)getWorkDefinitions()).basicRemove(otherEnd, msgs);
      case PDL3Package.PROCESS__WORK_SEQUENCES:
        return ((InternalEList<?>)getWorkSequences()).basicRemove(otherEnd, msgs);
      case PDL3Package.PROCESS__PROCESS_ELEMENTS:
        return ((InternalEList<?>)getProcessElements()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case PDL3Package.PROCESS__NAME:
        return getName();
      case PDL3Package.PROCESS__WORK_DEFINITIONS:
        return getWorkDefinitions();
      case PDL3Package.PROCESS__WORK_SEQUENCES:
        return getWorkSequences();
      case PDL3Package.PROCESS__PROCESS_ELEMENTS:
        return getProcessElements();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case PDL3Package.PROCESS__NAME:
        setName((String)newValue);
        return;
      case PDL3Package.PROCESS__WORK_DEFINITIONS:
        getWorkDefinitions().clear();
        getWorkDefinitions().addAll((Collection<? extends WorkDefinition>)newValue);
        return;
      case PDL3Package.PROCESS__WORK_SEQUENCES:
        getWorkSequences().clear();
        getWorkSequences().addAll((Collection<? extends WorkSequence>)newValue);
        return;
      case PDL3Package.PROCESS__PROCESS_ELEMENTS:
        getProcessElements().clear();
        getProcessElements().addAll((Collection<? extends ProcessElement>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case PDL3Package.PROCESS__NAME:
        setName(NAME_EDEFAULT);
        return;
      case PDL3Package.PROCESS__WORK_DEFINITIONS:
        getWorkDefinitions().clear();
        return;
      case PDL3Package.PROCESS__WORK_SEQUENCES:
        getWorkSequences().clear();
        return;
      case PDL3Package.PROCESS__PROCESS_ELEMENTS:
        getProcessElements().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case PDL3Package.PROCESS__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case PDL3Package.PROCESS__WORK_DEFINITIONS:
        return workDefinitions != null && !workDefinitions.isEmpty();
      case PDL3Package.PROCESS__WORK_SEQUENCES:
        return workSequences != null && !workSequences.isEmpty();
      case PDL3Package.PROCESS__PROCESS_ELEMENTS:
        return processElements != null && !processElements.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(')');
    return result.toString();
  }

} //ProcessImpl
