/**
 * generated by Xtext 2.38.0
 */
package fr.n7.pDL3;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Process</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.pDL3.Process#getName <em>Name</em>}</li>
 *   <li>{@link fr.n7.pDL3.Process#getWorkDefinitions <em>Work Definitions</em>}</li>
 *   <li>{@link fr.n7.pDL3.Process#getWorkSequences <em>Work Sequences</em>}</li>
 *   <li>{@link fr.n7.pDL3.Process#getProcessElements <em>Process Elements</em>}</li>
 * </ul>
 *
 * @see fr.n7.pDL3.PDL3Package#getProcess()
 * @model
 * @generated
 */
public interface Process extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see fr.n7.pDL3.PDL3Package#getProcess_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link fr.n7.pDL3.Process#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Work Definitions</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.pDL3.WorkDefinition}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Work Definitions</em>' containment reference list.
   * @see fr.n7.pDL3.PDL3Package#getProcess_WorkDefinitions()
   * @model containment="true"
   * @generated
   */
  EList<WorkDefinition> getWorkDefinitions();

  /**
   * Returns the value of the '<em><b>Work Sequences</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.pDL3.WorkSequence}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Work Sequences</em>' containment reference list.
   * @see fr.n7.pDL3.PDL3Package#getProcess_WorkSequences()
   * @model containment="true"
   * @generated
   */
  EList<WorkSequence> getWorkSequences();

  /**
   * Returns the value of the '<em><b>Process Elements</b></em>' containment reference list.
   * The list contents are of type {@link fr.n7.pDL3.ProcessElement}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Process Elements</em>' containment reference list.
   * @see fr.n7.pDL3.PDL3Package#getProcess_ProcessElements()
   * @model containment="true"
   * @generated
   */
  EList<ProcessElement> getProcessElements();

} // Process
