/**
 * generated by Xtext 2.38.0
 */
package fr.n7.pDL1;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ressource Allouee</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link fr.n7.pDL1.RessourceAllouee#getRessources <em>Ressources</em>}</li>
 *   <li>{@link fr.n7.pDL1.RessourceAllouee#getNumber <em>Number</em>}</li>
 * </ul>
 *
 * @see fr.n7.pDL1.PDL1Package#getRessourceAllouee()
 * @model
 * @generated
 */
public interface RessourceAllouee extends ProcessElement
{
  /**
   * Returns the value of the '<em><b>Ressources</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ressources</em>' reference.
   * @see #setRessources(Ressources)
   * @see fr.n7.pDL1.PDL1Package#getRessourceAllouee_Ressources()
   * @model
   * @generated
   */
  Ressources getRessources();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.RessourceAllouee#getRessources <em>Ressources</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ressources</em>' reference.
   * @see #getRessources()
   * @generated
   */
  void setRessources(Ressources value);

  /**
   * Returns the value of the '<em><b>Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number</em>' attribute.
   * @see #setNumber(int)
   * @see fr.n7.pDL1.PDL1Package#getRessourceAllouee_Number()
   * @model
   * @generated
   */
  int getNumber();

  /**
   * Sets the value of the '{@link fr.n7.pDL1.RessourceAllouee#getNumber <em>Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Number</em>' attribute.
   * @see #getNumber()
   * @generated
   */
  void setNumber(int value);

} // RessourceAllouee
